apiVersion: apps/v1
kind: Deployment
metadata:
  name: insights-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insights
  template:
    metadata:
      labels:
        app: insights
    spec:
      containers:
        - name: insights
          image: liran1789/insights
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name 
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: worksheeter
            - name: QUEUE_GROUP_NAME
              value: 'worksheets-service'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/insights/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: insights-srv
spec:
  selector:
    app: insights
  ports:
    - name: insights
      protocol: TCP
      port: 3000
      targetPort: 3000
