apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/**/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: worksheeter-468814
  artifacts:
    - image: us.gcr.io/worksheeter-468814/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/worksheeter-468814/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: us.gcr.io/worksheeter-468814/worksheets
      context: worksheets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/worksheeter-468814/ai-processor
      context: ai-processor
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/worksheeter-468814/quizzes
      context: quizzes
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/worksheeter-468814/insights
      context: insights
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/worksheeter-468814/coding
      context: coding
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/worksheeter-468814/sessions
      context: sessions
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .