apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coding
  template:
    metadata:
      labels:
        app: coding
    spec:
      containers:
        - name: coding
          image: liran1789/coding
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: worksheeter
            - name: QUEUE_GROUP_NAME
              value: 'coding-service'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: JUDGE0_API_URL
              value: 'https://judge0-ce.p.rapidapi.com'
            - name: JUDGE0_API_KEY
              valueFrom:
                secretKeyRef:
                  name: judge0-secret
                  key: JUDGE0_API_KEY
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/coding/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: coding-srv
spec:
  selector:
    app: coding
  ports:
    - name: coding
      protocol: TCP
      port: 3000
      targetPort: 3000