apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  JWT_KEY: asdf
---
apiVersion: v1
kind: Secret
metadata:
  name: claude-secret
type: Opaque
stringData:
  CLAUDE_API_KEY: YOUR_CLAUDE_API_KEY_HERE